name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type to bump (patch, minor, major)'
        required: true
        default: 'patch'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm
        run: |
          cd ./src/
          npm install

      - name: Install dependencies
        run: |
          cd ./src/
          npm ci

      - name: Npm Version Patch
        run: |
          cd ./src/
          npm version ${{ github.event.inputs.version }}

      # FIXME: email, name
      - name: Git Commit
        run: |
          git config --global user.email ''
          git config --global user.name "unvus"
          git add .
          git commit -m "Bump Version"

      # FIXME: Secret Value
      - name: Publish to npm
        run: |
          cd ./src/
          npm publish --access public --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUB_TOKEN}}

      - name: git push
        run: git push origin main